### ISSUE TITLE
Custom grid is missing cells, and lacking titles

### ISSUE THREAD

**Issue by Eunoia** [hafen/geofacet#40] opened 2017-07-05 16:29 UTC
Hey Ryan,

Huge fan of geofacet, I love the visualizations that are possible with your library. 

I'm trying to make my own geofaceted visualization of San Francisco Bay Area unemployment, but I've run into layout issues with geofacet. 

I found data from the California Employment Development Department that breaks down the unemployment rate by county, by year. [This is the extract I'm using](https://gist.github.com/Eunoia/8c21d7856384b76d9b9f6e4c3af59e9f)

| Year | Period | Area           | Adjusted | Preliminary | Rate | 
|------|--------|----------------|----------|-------------|------| 
| 2016 | Annual | Alameda County | Not Adj  | Not Prelim  | 4.2  | 
| 2015 | Annual | Alameda County | Not Adj  | Not Prelim  | 4.7  | 
| 2014 | Annual | Alameda County | Not Adj  | Not Prelim  | 5.8  | 

Using the [Grid Designer](https://hafen.github.io/grid-designer/#data=code%2Cname%2Crow%2Ccol%0ASonoma%20County%2CSonoma%20County%2C1%2C1%0ANapa%20County%2CNapa%20County%2C1%2C2%0ASolano%20Count%2CSolano%20Count%2C1%2C3%0AMarin%20County%2CMarin%20County%2C2%2C1%0AContra%20Costa%20County%2CContra%20Costa%20County%2C2%2C3%0AAlameda%20County%2CAlameda%20County%2C3%2C3%0ASan%20Francisco%20County%2CSan%20Francisco%20County%2C3%2C1%0ASan%20Mateo%20County%2CSan%20Mateo%20County%2C4%2C1%0ASanta%20Clara%20County%2CSanta%20Clara%20County%2C4%2C2&img=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fd%2Fd8%2FCalifornia_Bay_Area_county_map_%2528zoom%2526color%2529.svg%2F465px-California_Bay_Area_county_map_%2528zoom%2526color%2529.svg.png), I was able to layout a nice grid that approximates the nine San Francisco Bay Area counties. 

With my data and grid in place, I created a an unemployment rate time series for each county.

```R
library(ggplot2)
library(geofacet)
library(readr)
library(dplyr)

bay_area_9_counties <- data.frame(
  code = c("Sonoma County", "Napa County", "Solano Count", "Marin County", "Contra Costa County", "Alameda County", "San Francisco County", "San Mateo County", "Santa Clara County"),
  name = c("Sonoma County", "Napa County", "Solano Count", "Marin County", "Contra Costa County", "Alameda County", "San Francisco County", "San Mateo County", "Santa Clara County"),
  row = c(1, 1, 1, 2, 2, 3, 3, 4, 4),
  col = c(1, 2, 3, 1, 3, 3, 1, 1, 2)
)

ca_unemployment <- read_csv("~/Downloads/DA20171555.txt",
                col_types = cols(Adjusted = col_skip(),
                                 Period = col_skip(), 
                                 Preliminary = col_skip())
)

bay = filter(ca_unemployment, Area %in% bay_area_9_counties$code)

ggplot(bay, aes(Year, Rate)) + 
  geom_line(color='steelblue') + 
  facet_geo(~ Area, grid = bay_area_9_counties, label = "name") + 
  scale_x_continuous(labels = function(x) paste0("'", substr(x, 3, 4))) +
  theme_bw() + ggsave('weirdplot.png')

```

The resulting geofacet is little off, with San Francisco, San Mateo, and Solano Counties not bring present. 

![weirdplot](https://user-images.githubusercontent.com/934880/27874011-e22c2894-6162-11e7-84a1-26cc59598799.png)

I've tried rearranging the layout of the grid, removing the lacuna of 'bay' in the center. Adding fake counties, removing counties, reloading my R environment, reinstalling geofacet. There has been no positive effect on the layout of the visualization.

I'm running R version 3.3.3, on OS X El Capitan, with:
 * dplyr 0.5.0
 * readr 1.0.0
 * geofacet 0.1.4
 * ggplot2_2.2.1 

[This gist](https://gist.github.com/Eunoia/44bd0c832f9f3e5b1fe2d679762901e5) is the output of sessionInfo. 

While the data has no NAs, I'm getting this warning, which may be relevent.

```
Warning message:
In `[<-.factor`(`*tmp*`, na_idx, value = c(" ", "  ", "   ")) :
  invalid factor level, NA generated
```

I really love what you've done with this library, and been impressed with what [other](https://github.com/nateapathy/BCRA_CAP) [people](http://textura.in.ua/) have accomplished.

Do you have any suggestions about how I can get my geo's to facet properly?

**Comment by hafen** [comment] 2017-07-06 04:33
Thanks for the reproducible example (and for submitting your grid as well - I'll add it in as soon as I have the chance).

It turns out that the issue simply has to do with the fact that you are using `data.frame()` to create your grid and it is storing the codes as factors by default, which geofacet for some reason doesn't like. This is my fault since the grid designer provides the code that gives the error. Please leave this open and I'll fix it in the designer and make the R package deal with it appropriately when I get back in the office next week.

For now, you can fix the issue with the following:

```r
bay_area_9_counties <- data.frame(
  code = c("Sonoma County", "Napa County", "Solano County", "Marin County", "Contra Costa County", "Alameda County", "San Francisco County", "San Mateo County", "Santa Clara County"),
  name = c("Sonoma County", "Napa County", "Solano County", "Marin County", "Contra Costa County", "Alameda County", "San Francisco County", "San Mateo County", "Santa Clara County"),
  row = c(1, 1, 1, 2, 2, 3, 3, 4, 4),
  col = c(1, 2, 3, 1, 3, 3, 1, 1, 2),
  stringsAsFactors = FALSE
)
```

Also note that I added a "y" to "Solano Count(y)" so that the data for that county gets included as well.

**Comment by hafen** [comment] 2017-07-10 18:01
This has been fixed with recent commits.

**Closed by hafen** 2017-07-10 18:01 UTC
