### ISSUE TITLE
new grid: 'Georgia Grid'

### ISSUE THREAD

**Issue by nasrashvilin** [hafen/geofacet#347] opened 2021-09-02 18:07 UTC
Regions of Republic of Georgia

[[Note: To help streamline the process of adding this grid, please replace this text with an image of a map for the region for reference. Also, please check the ISO_3166-2 (https://en.wikipedia.org/wiki/ISO_3166-2) codes if your grid uses countries or states/provinces. Finally, if you can provide an example of your grid in action with a data set and sample code, that would be great but is not required.]]

Grid data:

```
"row","col","code","name_en"
1,1,"AB","Abkhazia"
2,3,"RC","Racha"
2,4,"TS","Tskhinvali"
2,2,"SM","Samegrelo"
2,5,"TI","Mtskheta-Mtianeti"
3,4,"SH","Shida Kartli"
3,3,"IM","Imereti"
3,5,"TB","Tbilisi"
3,2,"GR","Guria"
4,6,"KA","Kakheti"
4,3,"SJ","Samtskhe-Javakheti"
4,2,"AD","Adjara"
4,5,"KV","Kvemo Kartli"
```

**Comment by stedy** [comment] 2021-11-11 20:49
Duplicate of https://github.com/hafen/geofacet/issues/320

**Closed by stedy** 2021-11-11 20:49 UTC
